### ISSUE TITLE
getting invalid ELF header error in amazon lambda 

### ISSUE THREAD

**Issue by techjewel** [crisp-oss/email-reply-parser#15]
I am deploying a super simple lambda function using serverless. 
When I am invoking the function, I get the following error:
```
{
    "errorType": "Error",
    "errorMessage": "/var/task/node_modules/re2/build/Release/re2.node: invalid ELF header",
    "trace": [
        "Error: /var/task/node_modules/re2/build/Release/re2.node: invalid ELF header",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Module.require (internal/modules/cjs/loader.js:974:19)",
        "    at require (internal/modules/cjs/helpers.js:101:18)",
        "    at Object.<anonymous> (/var/task/node_modules/re2/re2.js:3:13)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)"
    ]
}
```

Any idea, how I can resolve the issue as email-reply-parser is the only library is using the re2.node

Thanks in advance

**Comment by valeriansaliou** [comment]
Looks like the architecture of the underlying CPU running AWS Lambda code is not compatible w/ one of our dependency. This issue is likely on `re2`, not this library.

**Comment by valeriansaliou** [comment]
This issue is similar to yours: https://stackoverflow.com/questions/29994411/invalid-elf-header-when-using-the-nodejs-ref-module-on-aws-lambda

From what I understand, the issue is unrelated to this library.

**Comment by baptistejamin** [comment]
This library didn't use Re2 a year ago. What could be possible is using an older version: https://github.com/crisp-oss/email-reply-parser/commit/05bd511629a8b08646dbe4d4e64e7b6aeb3bc9c9, for instance, 1.4.0

**Comment by bart** [comment]
I cannot understand why this issue got closed. Facing the same issue here without any success.

**Comment by vandanafuletra** [comment]
@baptistejamin This library is coming as a dependency to your page. There could be a possible way on how the library can be used on AWS Lambda function. 


```
└─┬ email-reply-parser@1.4.2
  └── re2@1.17.7 
```

**Comment by deathemperor** [comment]
got the same issue with Lambda, which is re2

```
 "TypeError: Cannot set properties of undefined (setting 'Symbol(Symbol.match)')",
        "    at <anonymous> (/node_modules/re2/re2.js:7:32)",
```
