### ISSUE TITLE
Request: fragments should have clear body and sender information

### ISSUE THREAD

**Issue by aiavci** [crisp-oss/email-reply-parser#17]
### Summary
Fragments have a `content` property. It would be great to have these broken into `body` and the sender information

**Comment by baptistejamin** [comment]
We chose to keep the lib as simple as possible.

Getting sender information is to me the Job for a different library or a mail parser.

I think with the state of LLMs, it should be possible to create a dead simple LLM that would do this job using a seq2seq arch our a masking architecture

Regexes are
